usuario_login:
    path:     /usuarios/login
    defaults: { _controller: DojoLoginBundle:Default:login }

usuario_login_check:
    pattern: /usuarios/login_check
    
usuario_logout:
    pattern: /usuarios/logout
    
dashboard:
    pattern: /usuarios/dashboard
    defaults: { _controller: DojoLoginBundle:Default:dashboard }