parameters:
#    dojo_login.example:
#        class: Dojo\LoginBundle\Example

services:
    login_listener:
        class: Dojo\LoginBundle\Listener\LoginListener
        scope: container
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
