security:
    firewalls:
        backend:
            pattern:        ^/backend
            provider:       administradores
            http_basic:     ~
            
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: /dashboard
            logout:
                path:       usuario_logout
            remember_me:
                key:        dojo
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana                 
    access_control:
        - { path: ^/,                 roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,            roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard,        roles: ROLE_USUARIO }
        - { path: ^/backend/*,        roles: ROLE_ADMIN }
        
    providers:
        usuarios:
            entity: { class: Dojo\LoginBundle\Entity\Usuario, property: email }     
            
        administradores:
            memory:
                users:
                    # user = admin, pass = 1234
                    admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }    
                    
    encoders:
        Dojo\LoginBundle\Entity\Usuario: { algorithm: sha512, iterations: 10}
        Symfony\Component\Security\Core\User\User: sha512
        

        
        