dojo_backend_asignaturas:
    resource: "@DojoBackendBundle/Resources/config/routing/asignaturas.yml"
    prefix:   /asignaturas

dojo_backend_modulos:
    resource: "@DojoBackendBundle/Resources/config/routing/modulos.yml"
    prefix:   /modulos