<?php

namespace Dojo\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturasRepository extends EntityRepository
{
    public function BuscarAsignaturasParaAlumno($IdAlumno)
    {
        
        $em = $this->getDoctrine()->getEntityManager();   
        $dql = "select asignaturas from DojoBackendBundle:Alumnos_Asignaturas relacion"
                . " join relacion.asignaturas asignaturas "
                . " where relacion.alumno := alumno";
          
        $query = $em->createQuery($dql);
        $query->setParameter('alumno', $idAlumno);
        $asignaturas = $query->getResult();;
        
        return $asignaturas;       
    }
}
