asignaturas:
    path:     /
    defaults: { _controller: "DojoBackendBundle:Asignaturas:index" }

asignaturas_show:
    path:     /{id}/show
    defaults: { _controller: "DojoBackendBundle:Asignaturas:show" }

asignaturas_new:
    path:     /new
    defaults: { _controller: "DojoBackendBundle:Asignaturas:new" }

asignaturas_create:
    path:     /create
    defaults: { _controller: "DojoBackendBundle:Asignaturas:create" }
    requirements: { _method: post }

asignaturas_edit:
    path:     /{id}/edit
    defaults: { _controller: "DojoBackendBundle:Asignaturas:edit" }

asignaturas_update:
    path:     /{id}/update
    defaults: { _controller: "DojoBackendBundle:Asignaturas:update" }
    requirements: { _method: post|put }

asignaturas_delete:
    path:     /{id}/delete
    defaults: { _controller: "DojoBackendBundle:Asignaturas:delete" }
    requirements: { _method: post|delete }
